version: '3.7'

services:
  db:
    container_name: mariadb
    image: mariadb:10
    ports:
      - 3308:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: ./db/connection
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always

  koa:
    container_name: board
    image: board-image
    environment:
      TZ: "Asia/Seoul"
    build:
      context: .
      # dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    networks:
      - backend
    volumes: 
      - ./:/app

volumes:
  data:
    driver: local
    
networks:
  backend:
    driver: bridge
